package com.supermercadodw.entidades;
// Generated 08/07/2018 09:58:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private Tarjeta tarjeta;
     private String nombreCliente;
     private String apellidoPaternoCliente;
     private String apellidoMaternoCliente;
     private Integer cantidadPuntos;
     private Integer dniCliente;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, Tarjeta tarjeta) {
        this.idCliente = idCliente;
        this.tarjeta = tarjeta;
    }
    public Cliente(int idCliente, Tarjeta tarjeta, String nombreCliente, String apellidoPaternoCliente, String apellidoMaternoCliente, Integer cantidadPuntos, Integer dniCliente, Set ventas) {
       this.idCliente = idCliente;
       this.tarjeta = tarjeta;
       this.nombreCliente = nombreCliente;
       this.apellidoPaternoCliente = apellidoPaternoCliente;
       this.apellidoMaternoCliente = apellidoMaternoCliente;
       this.cantidadPuntos = cantidadPuntos;
       this.dniCliente = dniCliente;
       this.ventas = ventas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoPaternoCliente() {
        return this.apellidoPaternoCliente;
    }
    
    public void setApellidoPaternoCliente(String apellidoPaternoCliente) {
        this.apellidoPaternoCliente = apellidoPaternoCliente;
    }
    public String getApellidoMaternoCliente() {
        return this.apellidoMaternoCliente;
    }
    
    public void setApellidoMaternoCliente(String apellidoMaternoCliente) {
        this.apellidoMaternoCliente = apellidoMaternoCliente;
    }
    public Integer getCantidadPuntos() {
        return this.cantidadPuntos;
    }
    
    public void setCantidadPuntos(Integer cantidadPuntos) {
        this.cantidadPuntos = cantidadPuntos;
    }
    public Integer getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(Integer dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


