package com.supermercadodw.entidades;
// Generated 10/07/2018 12:24:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int dniCliente;
     private Tarjeta tarjeta;
     private String nombreCliente;
     private String apellidoPaternoCliente;
     private String apellidoMaternoCliente;
     private Integer cantidadPuntos;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int dniCliente, Tarjeta tarjeta) {
        this.dniCliente = dniCliente;
        this.tarjeta = tarjeta;
    }
    public Cliente(int dniCliente, Tarjeta tarjeta, String nombreCliente, String apellidoPaternoCliente, String apellidoMaternoCliente, Integer cantidadPuntos, Set ventas) {
       this.dniCliente = dniCliente;
       this.tarjeta = tarjeta;
       this.nombreCliente = nombreCliente;
       this.apellidoPaternoCliente = apellidoPaternoCliente;
       this.apellidoMaternoCliente = apellidoMaternoCliente;
       this.cantidadPuntos = cantidadPuntos;
       this.ventas = ventas;
    }
   
    public int getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(int dniCliente) {
        this.dniCliente = dniCliente;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoPaternoCliente() {
        return this.apellidoPaternoCliente;
    }
    
    public void setApellidoPaternoCliente(String apellidoPaternoCliente) {
        this.apellidoPaternoCliente = apellidoPaternoCliente;
    }
    public String getApellidoMaternoCliente() {
        return this.apellidoMaternoCliente;
    }
    
    public void setApellidoMaternoCliente(String apellidoMaternoCliente) {
        this.apellidoMaternoCliente = apellidoMaternoCliente;
    }
    public Integer getCantidadPuntos() {
        return this.cantidadPuntos;
    }
    
    public void setCantidadPuntos(Integer cantidadPuntos) {
        this.cantidadPuntos = cantidadPuntos;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


