package com.supermercadodw.entidades;
// Generated 10/07/2018 11:48:39 AM by Hibernate Tools 4.3.1



/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private Integer idDetalleVenta;
     private Producto producto;
     private Venta venta;
     private Integer cantidadProductoVenta;
     private String montoFinalProductoVenta;

    public DetalleVenta() {
    }

	
    public DetalleVenta(Producto producto, Venta venta) {
        this.producto = producto;
        this.venta = venta;
    }
    public DetalleVenta(Producto producto, Venta venta, Integer cantidadProductoVenta, String montoFinalProductoVenta) {
       this.producto = producto;
       this.venta = venta;
       this.cantidadProductoVenta = cantidadProductoVenta;
       this.montoFinalProductoVenta = montoFinalProductoVenta;
    }
   
    public Integer getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(Integer idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidadProductoVenta() {
        return this.cantidadProductoVenta;
    }
    
    public void setCantidadProductoVenta(Integer cantidadProductoVenta) {
        this.cantidadProductoVenta = cantidadProductoVenta;
    }
    public String getMontoFinalProductoVenta() {
        return this.montoFinalProductoVenta;
    }
    
    public void setMontoFinalProductoVenta(String montoFinalProductoVenta) {
        this.montoFinalProductoVenta = montoFinalProductoVenta;
    }




}


