package com.supermercadodw.entidades;
// Generated 08/07/2018 09:17:20 PM by Hibernate Tools 4.3.1



/**
 * Detalleproducto generated by hbm2java
 */
public class Detalleproducto  implements java.io.Serializable {


     private int idDetalleProducto;
     private Producto producto;
     private Venta venta;
     private Integer cantidadProductoCompra;

    public Detalleproducto() {
    }

	
    public Detalleproducto(int idDetalleProducto, Producto producto, Venta venta) {
        this.idDetalleProducto = idDetalleProducto;
        this.producto = producto;
        this.venta = venta;
    }
    public Detalleproducto(int idDetalleProducto, Producto producto, Venta venta, Integer cantidadProductoCompra) {
       this.idDetalleProducto = idDetalleProducto;
       this.producto = producto;
       this.venta = venta;
       this.cantidadProductoCompra = cantidadProductoCompra;
    }
   
    public int getIdDetalleProducto() {
        return this.idDetalleProducto;
    }
    
    public void setIdDetalleProducto(int idDetalleProducto) {
        this.idDetalleProducto = idDetalleProducto;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Integer getCantidadProductoCompra() {
        return this.cantidadProductoCompra;
    }
    
    public void setCantidadProductoCompra(Integer cantidadProductoCompra) {
        this.cantidadProductoCompra = cantidadProductoCompra;
    }




}


