package com.supermercadodw.entidades;
// Generated 11/07/2018 01:39:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String idProducto;
     private String nombreProducto;
     private Float precioProducto;
     private String descripcionProducto;
     private Integer cantidadProducto;
     private Integer cantidadPuntos;
     private Set detalleVentas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(String idProducto, String nombreProducto, Float precioProducto, String descripcionProducto, Integer cantidadProducto, Integer cantidadPuntos, Set detalleVentas) {
       this.idProducto = idProducto;
       this.nombreProducto = nombreProducto;
       this.precioProducto = precioProducto;
       this.descripcionProducto = descripcionProducto;
       this.cantidadProducto = cantidadProducto;
       this.cantidadPuntos = cantidadPuntos;
       this.detalleVentas = detalleVentas;
    }
   
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Float getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(Float precioProducto) {
        this.precioProducto = precioProducto;
    }
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }
    public Integer getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(Integer cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public Integer getCantidadPuntos() {
        return this.cantidadPuntos;
    }
    
    public void setCantidadPuntos(Integer cantidadPuntos) {
        this.cantidadPuntos = cantidadPuntos;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


