package com.supermercadodw.entidades;
// Generated 08/07/2018 09:58:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String idProducto;
     private String nombreProducto;
     private Float precioProducto;
     private String descripcionProducto;
     private Integer cantidadProducto;
     private Set detalleProductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(String idProducto, String nombreProducto, Float precioProducto, String descripcionProducto, Integer cantidadProducto, Set detalleProductos) {
       this.idProducto = idProducto;
       this.nombreProducto = nombreProducto;
       this.precioProducto = precioProducto;
       this.descripcionProducto = descripcionProducto;
       this.cantidadProducto = cantidadProducto;
       this.detalleProductos = detalleProductos;
    }
   
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Float getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(Float precioProducto) {
        this.precioProducto = precioProducto;
    }
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }
    public Integer getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(Integer cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public Set getDetalleProductos() {
        return this.detalleProductos;
    }
    
    public void setDetalleProductos(Set detalleProductos) {
        this.detalleProductos = detalleProductos;
    }




}


