package com.supermercadodw.entidades;
// Generated 11/07/2018 01:39:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private Integer idTarjeta;
     private Integer puntosTarjeta;
     private Set clientes = new HashSet(0);

    public Tarjeta() {
    }

    public Tarjeta(Integer puntosTarjeta, Set clientes) {
       this.puntosTarjeta = puntosTarjeta;
       this.clientes = clientes;
    }
   
    public Integer getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(Integer idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Integer getPuntosTarjeta() {
        return this.puntosTarjeta;
    }
    
    public void setPuntosTarjeta(Integer puntosTarjeta) {
        this.puntosTarjeta = puntosTarjeta;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


