package com.supermercadodw.entidades;
// Generated 08/07/2018 09:58:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private int idTarjeta;
     private Integer puntosTarjeta;
     private Set clientes = new HashSet(0);

    public Tarjeta() {
    }

	
    public Tarjeta(int idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Tarjeta(int idTarjeta, Integer puntosTarjeta, Set clientes) {
       this.idTarjeta = idTarjeta;
       this.puntosTarjeta = puntosTarjeta;
       this.clientes = clientes;
    }
   
    public int getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(int idTarjeta) {
        this.idTarjeta = idTarjeta;
    }
    public Integer getPuntosTarjeta() {
        return this.puntosTarjeta;
    }
    
    public void setPuntosTarjeta(Integer puntosTarjeta) {
        this.puntosTarjeta = puntosTarjeta;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


