package com.supermercadodw.entidades;
// Generated 08/07/2018 09:17:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idVenta;
     private Cliente cliente;
     private Personal personal;
     private Date fechaVenta;
     private Float montoVenta;
     private Set detalleproductos = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idVenta, Cliente cliente, Personal personal) {
        this.idVenta = idVenta;
        this.cliente = cliente;
        this.personal = personal;
    }
    public Venta(int idVenta, Cliente cliente, Personal personal, Date fechaVenta, Float montoVenta, Set detalleproductos) {
       this.idVenta = idVenta;
       this.cliente = cliente;
       this.personal = personal;
       this.fechaVenta = fechaVenta;
       this.montoVenta = montoVenta;
       this.detalleproductos = detalleproductos;
    }
   
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Float getMontoVenta() {
        return this.montoVenta;
    }
    
    public void setMontoVenta(Float montoVenta) {
        this.montoVenta = montoVenta;
    }
    public Set getDetalleproductos() {
        return this.detalleproductos;
    }
    
    public void setDetalleproductos(Set detalleproductos) {
        this.detalleproductos = detalleproductos;
    }




}


