package com.supermercadodw.entidades;
// Generated 10/07/2018 11:48:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Cliente cliente;
     private Personal personal;
     private Date fechaVenta;
     private Float montoVenta;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(Cliente cliente, Personal personal) {
        this.cliente = cliente;
        this.personal = personal;
    }
    public Venta(Cliente cliente, Personal personal, Date fechaVenta, Float montoVenta, Set detalleVentas) {
       this.cliente = cliente;
       this.personal = personal;
       this.fechaVenta = fechaVenta;
       this.montoVenta = montoVenta;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public Float getMontoVenta() {
        return this.montoVenta;
    }
    
    public void setMontoVenta(Float montoVenta) {
        this.montoVenta = montoVenta;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


